In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [90]:
n = 2
m = 2
x = np.array([-1/2, -1/6])
y = np.array([1/4, 1/30])

In [3]:
beta_1m = 1
beta_2m = 1
alpha_m = 1

In [91]:
a = np.random.normal(loc=0, scale=beta_1m**2, size=(m))
w = np.random.normal(loc=0, scale=beta_2m**2, size=(m))
b = np.random.normal(loc=0, scale=beta_2m**2, size=(m))

a,w,b

(array([1.40441705, 0.02208055]),
 array([ 0.0047783 , -0.08436851]),
 array([-1.41492208,  0.74269956]))

In [75]:
def relu(x):
    return np.maximum(0, x)

def indicator(condition):
    return condition.astype(int)

In [84]:
def gradient_flow(a,w,b):
    grad_a = -(1/n) * np.sum([[(1/alpha_m) * relu((w*x[i])+b) * gradRiskwrtFunction(a,w,b,i)] for i in range(n)], axis=0)
    grad_w = -(1/n) * np.sum([[(1/alpha_m) * a*x[i] * indicator(w*x[i]+b > 0) * gradRiskwrtFunction(a,w,b,i)] for i in range(n)], axis=0)
    grad_b = -(1/n) * np.sum([[(1/alpha_m) * a * indicator(w*x[i]+b > 0) * gradRiskwrtFunction(a,w,b,i)] for i in range(n)], axis=0)
    return grad_a, grad_w, grad_b

def gradRiskwrtFunction(a,w,b,i):
    return 1/alpha_m * np.sum([[a[j] * relu((w[j]*x[i])+b[j]) - y[i]] for j in range(m)], axis=0)


In [92]:
gradient_flow(a,w,b)

(array([[-0.        ,  0.20832241]]),
 array([[-0.        , -0.00275632]]),
 array([[-0.        ,  0.00588034]]))